version: '3'
services:
  dbmysql:
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=db_musicas
  app:
    environment:
      - PGHOST=dbpostgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGDATABASE=db_playlists
      - MYSQL_HOST=dbmysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=db_musicas