version: '3'
volumes:
  datadbpostgres:
  datadbmysql: 
networks:
  database:
  web:
services: 
  dbpostgres: 
    image: postgres:9.6
    volumes:
      # Volume dos dados
      - datadbpostgres:/var/lib/postgresql/data
      # Scripts
      - ./db/postgres/scripts:/scripts
      - ./db/postgres/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - database
  dbmysql: 
    image: mysql:5.7
    volumes:
      # Volume dos dados
      - datadbmysql:/var/lib/mysql
      # Scripts
      - ./db/mysql/scripts:/scripts
      - ./db/mysql/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - database
  balancer:
      image: nginx:1.13
      volumes:
        # Configuração do balancer
        - ./balancer/default.config:/etc/nginx/conf.d/default.conf
      ports:
        - 80:80
      networks:
        - web
      depends_on:
        - frontend
  frontend:
      image: nginx:1.13
      volumes:
        # Site
        - ./web:/usr/share/nginx/html/
        # Configuração do proxy reverso
        - ./nginx/default.config:/etc/nginx/conf.d/default.conf
      expose:
        - 80
      networks:
        - web
      depends_on:
        - app
  app:
    image: node:8.1
    restart: always
    volumes:
      # Aplicação
      - ./app:/app
    working_dir: /app
    command: bash -c "npm install && node bin/www"
    networks:
      - database
      - web
    depends_on:
      - dbpostgres
      - dbmysql